// Generated by scripts/generate_protocol.py; DO NOT EDIT.
// schema-sha256: 141c396d5b0abc120bf94db5ea1c2707c67fc008a2dc4eba06f9c52caa71526d

export type JsonValue = null | boolean | number | string | Array<JsonValue> | { [key: string]: JsonValue }

export interface EventScope {
  tenant_id: string
  project_id: string
  agent_id?: string | null
  organization_id?: string | null
}

export interface SessionEvent {
  schema_version: "1.0"
  session_id: string
  seq: number
  type: string
  ts: string
  scope: EventScope
  payload: { [key: string]: JsonValue }
  ignorable: boolean
}

export interface MutationMeta {
  request_id: string
  idempotency_key: string
  session_revision: number
}

export interface ProtocolHello {
  protocol_version: "1.0"
  event_schema_version: "1.0"
  capabilities: Array<string>
}

export interface RpcRequest {
  jsonrpc: "2.0"
  id: string
  method: string
  params: { [key: string]: JsonValue }
  mutation?: MutationMeta
}

export interface RpcSuccess {
  jsonrpc: "2.0"
  id: string
  result: JsonValue
}

export interface RpcError {
  code: string
  message: string
  retryable: boolean
  details?: { [key: string]: JsonValue }
}

export interface RpcFailure {
  jsonrpc: "2.0"
  id: string | null
  error: RpcError
}

export interface PluginPermission {
  kind: "network" | "filesystem" | "process" | "credential"
  resources: Array<string>
  reason?: string | null
}

export interface PluginManifest {
  name: string
  version: string
  api_version: "1"
  dependencies: { [key: string]: string }
  requires: Array<string>
  provides: Array<string>
  config_schema: { [key: string]: JsonValue }
  permissions: Array<PluginPermission>
}
