"""Generated by scripts/generate_protocol.py; DO NOT EDIT."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

SCHEMA_SHA256 = "f1df08ff017474b429e122475ae618c58f7424ecf87995f5fb5dba982b2c65d9"

JsonValue = TypeAliasType("JsonValue", None | bool | int | float | str | list['JsonValue'] | dict[str, 'JsonValue'])

class EventScope(BaseModel):
    model_config = ConfigDict(extra="forbid")
    tenant_id: Annotated[str, Field(min_length=1)]
    project_id: Annotated[str, Field(min_length=1)]
    agent_id: str | None = None
    organization_id: str | None = None

class SessionEvent(BaseModel):
    model_config = ConfigDict(extra="forbid")
    schema_version: Literal['1.0']
    session_id: Annotated[str, Field(min_length=1)]
    seq: Annotated[int, Field(ge=1)]
    type: Annotated[str, Field(pattern='^[a-z][a-z0-9]*(\\.[a-z][a-z0-9_-]*)+$')]
    ts: datetime
    scope: EventScope
    payload: dict[str, JsonValue]
    ignorable: bool

class MutationMeta(BaseModel):
    model_config = ConfigDict(extra="forbid")
    request_id: Annotated[str, Field(min_length=1)]
    idempotency_key: Annotated[str, Field(min_length=1)]
    session_revision: Annotated[int, Field(ge=0)]

class ProtocolHello(BaseModel):
    model_config = ConfigDict(extra="forbid")
    protocol_version: Literal['1.0']
    event_schema_version: Literal['1.0']
    capabilities: list[str]

class RpcRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    jsonrpc: Literal['2.0']
    id: Annotated[str, Field(min_length=1)]
    method: Annotated[str, Field(min_length=1)]
    params: dict[str, JsonValue]
    mutation: MutationMeta | None = None

class RpcSuccess(BaseModel):
    model_config = ConfigDict(extra="forbid")
    jsonrpc: Literal['2.0']
    id: str
    result: JsonValue

class RpcError(BaseModel):
    model_config = ConfigDict(extra="forbid")
    code: str
    message: str
    retryable: bool
    details: dict[str, JsonValue] | None = None

class RpcFailure(BaseModel):
    model_config = ConfigDict(extra="forbid")
    jsonrpc: Literal['2.0']
    id: str | None
    error: RpcError

class PluginPermission(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal['network', 'filesystem', 'process', 'credential']
    resources: list[str]
    reason: str | None = None

class PluginManifest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: Annotated[str, Field(pattern='^[a-z][a-z0-9-]*(/[a-z][a-z0-9-]*)?$')]
    version: str
    api_version: Literal['1']
    dependencies: dict[str, str]
    provides: list[str]
    config_schema: dict[str, JsonValue]
    permissions: list[PluginPermission]
