// Generated by scripts/generate_protocol.py; DO NOT EDIT.
// schema-sha256: f1df08ff017474b429e122475ae618c58f7424ecf87995f5fb5dba982b2c65d9

export type JsonValue = null | boolean | number | string | Array<JsonValue> | Record<string, JsonValue>

export interface EventScope {
  tenant_id: string
  project_id: string
  agent_id?: string | null
  organization_id?: string | null
}

export interface SessionEvent {
  schema_version: "1.0"
  session_id: string
  seq: number
  type: string
  ts: string
  scope: EventScope
  payload: Record<string, JsonValue>
  ignorable: boolean
}

export interface MutationMeta {
  request_id: string
  idempotency_key: string
  session_revision: number
}

export interface ProtocolHello {
  protocol_version: "1.0"
  event_schema_version: "1.0"
  capabilities: Array<string>
}

export interface RpcRequest {
  jsonrpc: "2.0"
  id: string
  method: string
  params: Record<string, JsonValue>
  mutation?: MutationMeta
}

export interface RpcSuccess {
  jsonrpc: "2.0"
  id: string
  result: JsonValue
}

export interface RpcError {
  code: string
  message: string
  retryable: boolean
  details?: Record<string, JsonValue>
}

export interface RpcFailure {
  jsonrpc: "2.0"
  id: string | null
  error: RpcError
}

export interface PluginPermission {
  kind: "network" | "filesystem" | "process" | "credential"
  resources: Array<string>
  reason?: string | null
}

export interface PluginManifest {
  name: string
  version: string
  api_version: "1"
  dependencies: Record<string, string>
  provides: Array<string>
  config_schema: Record<string, JsonValue>
  permissions: Array<PluginPermission>
}
