{{- if .Values.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-cluster.fullname" . }}
  labels:
    {{- include "agent-cluster.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-token: {{ .Values.auth.token | quote }}
{{- end }}
