"""agent_cluster — 多 agent 组织型全栈开发集群运行时（Python + LangGraph）。

当前阶段覆盖：数据模型层（models.py）、技能层（skills.py）、流程引擎
（workflow.py）、审批门（gates.py）、组织角色（roles.py）、角色执行运行时
（runtime.py）、会议（meetings.py）、账本/任务板（ledger.py）、进化闭环
（evolution.py）、绩效度量（metrics.py）、工具执行层（tools.py）、MCP 客户端
（mcp_client.py）、会话构建（session.py）与 CLI（cli.py）；v0.4 新增环境预检
（doctor.py）、插件层（plugins.py）、连续开发 REPL（repl.py）、Docker 沙箱
（sandbox.py）、git worktree 隔离（worktree.py）与有界子代理（subagent.py）。
"""

from agent_cluster.models import (
    ActionRequest,
    Agent,
    AgentConfig,
    AgentState,
    ApprovalGate,
    ApprovalRecord,
    ClusterState,
    ContextConfig,
    Decision,
    Event,
    GateKind,
    HumanInterruptConfig,
    HumanResponse,
    InjectionConfig,
    Iteration,
    Ledger,
    Meeting,
    MeetingKind,
    Message,
    MessageType,
    ModelConfig,
    ProgressEntry,
    Project,
    Proposal,
    ProposalStatus,
    ProposalTarget,
    ReActConfig,
    Role,
    RoleKind,
    Skill,
    Task,
    TaskStatus,
    Vote,
)
from agent_cluster.workflow import (
    CompiledWorkflow,
    NodeContext,
    NodeHandler,
    WorkflowEdge,
    WorkflowEngine,
    WorkflowLoopError,
    WorkflowNode,
    WorkflowSpec,
    WorkflowValidationError,
)
from agent_cluster.gates import (
    GateError,
    approval_pending,
    make_gate_handler,
    resolve_auto_response,
)
from agent_cluster.roles import RoleRegistry, build_role_catalog
from agent_cluster.runtime import (
    AgentRuntime,
    ChatModelClient,
    ChatModelFactory,
    DeepSeekClient,
    DeterministicClient,
    EventBus,
    OpenAIClient,
    make_agent_handler,
)
from agent_cluster.meetings import MeetingHost, make_meeting_handler
from agent_cluster.ledger import BLOCKED, COLUMNS, LedgerStore, TaskBoard, TaskBoardError
from agent_cluster.evolution import (
    Candidate,
    EvolutionEngine,
    EvolutionError,
    EvolutionProposal,
    Signal,
)
from agent_cluster.metrics import (
    MetricPoint,
    MetricRules,
    MetricsCollector,
    MetricsSnapshot,
)
from agent_cluster.skills import (
    DisclosureLevel,
    SkillCatalog,
    SkillError,
    SkillFrontmatter,
    SkillLoader,
    SkillRegistry,
    format_skill_context,
)
from agent_cluster.projects import (
    BudgetPoolRecord,
    BudgetUnlockRecord,
    GatePolicyConfig,
    ProjectRecord,
    ProjectStore,
    SessionIndexEntry,
)

__version__ = "0.6.2"

__all__ = [
    "ActionRequest",
    "Agent",
    "AgentConfig",
    "AgentState",
    "ApprovalGate",
    "ApprovalRecord",
    "ClusterState",
    "ContextConfig",
    "Decision",
    "DisclosureLevel",
    "Event",
    "GateKind",
    "HumanInterruptConfig",
    "HumanResponse",
    "InjectionConfig",
    "Iteration",
    "Ledger",
    "Meeting",
    "MeetingKind",
    "Message",
    "MessageType",
    "ModelConfig",
    "ProgressEntry",
    "Project",
    "Proposal",
    "ProposalStatus",
    "ProposalTarget",
    "ReActConfig",
    "Role",
    "RoleKind",
    "Skill",
    "SkillCatalog",
    "SkillError",
    "SkillFrontmatter",
    "SkillLoader",
    "SkillRegistry",
    "Task",
    "TaskStatus",
    "Vote",
    "AgentRuntime",
    "ChatModelClient",
    "ChatModelFactory",
    "DeterministicClient",
    "EventBus",
    "OpenAIClient",
    "make_agent_handler",
    "MeetingHost",
    "make_meeting_handler",
    "LedgerStore",
    "TaskBoard",
    "TaskBoardError",
    "COLUMNS",
    "BLOCKED",
    "RoleRegistry",
    "build_role_catalog",
    "CompiledWorkflow",
    "NodeContext",
    "NodeHandler",
    "WorkflowEdge",
    "WorkflowEngine",
    "WorkflowLoopError",
    "WorkflowNode",
    "WorkflowSpec",
    "WorkflowValidationError",
    "__version__",
    "format_skill_context",
    "Candidate",
    "EvolutionEngine",
    "EvolutionError",
    "EvolutionProposal",
    "Signal",
    "MetricPoint",
    "MetricRules",
    "MetricsCollector",
    "MetricsSnapshot",
    "GateError",
    "approval_pending",
    "make_gate_handler",
    "resolve_auto_response",
    "BudgetPoolRecord",
    "BudgetUnlockRecord",
    "GatePolicyConfig",
    "ProjectRecord",
    "ProjectStore",
    "SessionIndexEntry",
]
