"""Generate TypeScript and Pydantic protocol types from the canonical schema."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "protocol" / "schema" / "doai-v1.schema.json"
TS_PATH = ROOT / "packages" / "protocol" / "src" / "generated.ts"
PY_PATH = ROOT / "src" / "doai_protocol" / "generated.py"


def _ref_name(schema: dict[str, Any]) -> str | None:
    ref = schema.get("$ref")
    return ref.rsplit("/", 1)[-1] if isinstance(ref, str) else None


def _ts_type(schema: dict[str, Any]) -> str:
    if ref := _ref_name(schema):
        return ref
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "oneOf" in schema:
        return " | ".join(_ts_type(item) for item in schema["oneOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(_ts_type({"type": item}) for item in kind)
    if kind == "null":
        return "null"
    if kind == "boolean":
        return "boolean"
    if kind in {"number", "integer"}:
        return "number"
    if kind == "string":
        return "string"
    if kind == "array":
        return f"Array<{_ts_type(schema.get('items', {}))}>"
    if kind == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"{{ [key: string]: {_ts_type(additional)} }}"
        return "{ [key: string]: unknown }"
    return "unknown"


def _py_type(schema: dict[str, Any], self_ref: str | None = None) -> str:
    if ref := _ref_name(schema):
        return repr(ref) if ref == self_ref else ref
    if "const" in schema:
        return f"Literal[{schema['const']!r}]"
    if "enum" in schema:
        values = ", ".join(repr(value) for value in schema["enum"])
        return f"Literal[{values}]"
    if "oneOf" in schema:
        return " | ".join(_py_type(item, self_ref) for item in schema["oneOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(_py_type({"type": item}, self_ref) for item in kind)
    if kind == "null":
        return "None"
    if kind == "boolean":
        return "bool"
    if kind == "integer":
        return "int"
    if kind == "number":
        return "int | float"
    if kind == "string":
        if schema.get("format") == "date-time":
            return "datetime"
        return "str"
    if kind == "array":
        return f"list[{_py_type(schema.get('items', {}), self_ref)}]"
    if kind == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"dict[str, {_py_type(additional, self_ref)}]"
        return "dict[str, Any]"
    return "Any"


def _py_field_type(schema: dict[str, Any]) -> str:
    base = _py_type(schema)
    constraints: list[str] = []
    for schema_name, field_name in (
        ("minimum", "ge"),
        ("maximum", "le"),
        ("minLength", "min_length"),
        ("maxLength", "max_length"),
        ("pattern", "pattern"),
    ):
        if schema_name in schema:
            constraints.append(f"{field_name}={schema[schema_name]!r}")
    if not constraints:
        return base
    return f"Annotated[{base}, Field({', '.join(constraints)})]"


def _render_ts(schema: dict[str, Any], digest: str) -> str:
    lines = [
        "// Generated by scripts/generate_protocol.py; DO NOT EDIT.",
        f"// schema-sha256: {digest}",
        "",
    ]
    for name, definition in schema["$defs"].items():
        if definition.get("type") != "object" or "properties" not in definition:
            lines.extend([f"export type {name} = {_ts_type(definition)}", ""])
            continue
        required = set(definition.get("required", []))
        lines.append(f"export interface {name} {{")
        for prop, prop_schema in definition["properties"].items():
            optional = "" if prop in required else "?"
            lines.append(f"  {prop}{optional}: {_ts_type(prop_schema)}")
        lines.extend(["}", ""])
    return "\n".join(lines)


def _render_python(schema: dict[str, Any], digest: str) -> str:
    lines = [
        '"""Generated by scripts/generate_protocol.py; DO NOT EDIT."""',
        "",
        "from __future__ import annotations",
        "",
        "from datetime import datetime",
        "from typing import Annotated, Any, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "from typing_extensions import TypeAliasType",
        "",
        f'SCHEMA_SHA256 = "{digest}"',
        "",
    ]
    definitions = schema["$defs"]
    for name, definition in definitions.items():
        if definition.get("type") != "object" or "properties" not in definition:
            value = _py_type(definition, name)
            lines.extend([f'{name} = TypeAliasType("{name}", {value})', ""])
            continue
        required = set(definition.get("required", []))
        lines.extend([f"class {name}(BaseModel):", '    model_config = ConfigDict(extra="forbid")'])
        for prop, prop_schema in definition["properties"].items():
            annotation = _py_field_type(prop_schema)
            default = "" if prop in required else " = None"
            if prop not in required and "None" not in annotation:
                annotation = f"{annotation} | None"
            lines.append(f"    {prop}: {annotation}{default}")
        lines.append("")
    return "\n".join(lines)


def _expected_outputs() -> dict[Path, str]:
    raw = SCHEMA_PATH.read_bytes()
    schema = json.loads(raw)
    digest = hashlib.sha256(raw).hexdigest()
    return {
        TS_PATH: _render_ts(schema, digest),
        PY_PATH: _render_python(schema, digest),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    stale: list[str] = []
    for path, expected in _expected_outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
    if stale:
        print("stale generated protocol files: " + ", ".join(stale))
        print("run: python scripts/generate_protocol.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
